/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Form: typeof import('./src/components/Form.vue')['default']
    FormBtn: typeof import('./src/components/FormBtn.vue')['default']
    IconBtn: typeof import('./src/components/IconBtn.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusCard: typeof import('./src/components/StatusCard.vue')['default']
    TaskCard: typeof import('./src/components/TaskCard.vue')['default']
  }
}
